// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRouters struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	HttpRouters   []*AgentRouters_HttpRouter `protobuf:"bytes,1,rep,name=http_routers,json=httpRouters,proto3" json:"http_routers,omitempty"`
	TcpRouters    []*AgentRouters_TcpRouter  `protobuf:"bytes,2,rep,name=tcp_routers,json=tcpRouters,proto3" json:"tcp_routers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRouters) Reset() {
	*x = AgentRouters{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRouters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRouters) ProtoMessage() {}

func (x *AgentRouters) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRouters.ProtoReflect.Descriptor instead.
func (*AgentRouters) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRouters) GetHttpRouters() []*AgentRouters_HttpRouter {
	if x != nil {
		return x.HttpRouters
	}
	return nil
}

func (x *AgentRouters) GetTcpRouters() []*AgentRouters_TcpRouter {
	if x != nil {
		return x.TcpRouters
	}
	return nil
}

type AgentRouters_HttpRouter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fqdn           string                 `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	HttpConnectTo  string                 `protobuf:"bytes,2,opt,name=http_connect_to,json=httpConnectTo,proto3" json:"http_connect_to,omitempty"`
	HttpsConnectTo string                 `protobuf:"bytes,3,opt,name=https_connect_to,json=httpsConnectTo,proto3" json:"https_connect_to,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRouters_HttpRouter) Reset() {
	*x = AgentRouters_HttpRouter{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRouters_HttpRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRouters_HttpRouter) ProtoMessage() {}

func (x *AgentRouters_HttpRouter) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRouters_HttpRouter.ProtoReflect.Descriptor instead.
func (*AgentRouters_HttpRouter) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AgentRouters_HttpRouter) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *AgentRouters_HttpRouter) GetHttpConnectTo() string {
	if x != nil {
		return x.HttpConnectTo
	}
	return ""
}

func (x *AgentRouters_HttpRouter) GetHttpsConnectTo() string {
	if x != nil {
		return x.HttpsConnectTo
	}
	return ""
}

type AgentRouters_TcpRouter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindTo        string                 `protobuf:"bytes,1,opt,name=bind_to,json=bindTo,proto3" json:"bind_to,omitempty"`
	ConnectTo     string                 `protobuf:"bytes,2,opt,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRouters_TcpRouter) Reset() {
	*x = AgentRouters_TcpRouter{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRouters_TcpRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRouters_TcpRouter) ProtoMessage() {}

func (x *AgentRouters_TcpRouter) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRouters_TcpRouter.ProtoReflect.Descriptor instead.
func (*AgentRouters_TcpRouter) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AgentRouters_TcpRouter) GetBindTo() string {
	if x != nil {
		return x.BindTo
	}
	return ""
}

func (x *AgentRouters_TcpRouter) GetConnectTo() string {
	if x != nil {
		return x.ConnectTo
	}
	return ""
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x06common\x1a\x1bgoogle/protobuf/empty.proto\"\xcc\x02\n" +
	"\fAgentRouters\x12B\n" +
	"\fhttp_routers\x18\x01 \x03(\v2\x1f.common.AgentRouters.HttpRouterR\vhttpRouters\x12?\n" +
	"\vtcp_routers\x18\x02 \x03(\v2\x1e.common.AgentRouters.TcpRouterR\n" +
	"tcpRouters\x1ar\n" +
	"\n" +
	"HttpRouter\x12\x12\n" +
	"\x04fqdn\x18\x01 \x01(\tR\x04fqdn\x12&\n" +
	"\x0fhttp_connect_to\x18\x02 \x01(\tR\rhttpConnectTo\x12(\n" +
	"\x10https_connect_to\x18\x03 \x01(\tR\x0ehttpsConnectTo\x1aC\n" +
	"\tTcpRouter\x12\x17\n" +
	"\abind_to\x18\x01 \x01(\tR\x06bindTo\x12\x1d\n" +
	"\n" +
	"connect_to\x18\x02 \x01(\tR\tconnectTo2>\n" +
	"\x04Ping\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB)Z'github.com/pikvm/cloud-api/proto/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_common_proto_goTypes = []any{
	(*AgentRouters)(nil),            // 0: common.AgentRouters
	(*AgentRouters_HttpRouter)(nil), // 1: common.AgentRouters.HttpRouter
	(*AgentRouters_TcpRouter)(nil),  // 2: common.AgentRouters.TcpRouter
	(*emptypb.Empty)(nil),           // 3: google.protobuf.Empty
}
var file_common_common_proto_depIdxs = []int32{
	1, // 0: common.AgentRouters.http_routers:type_name -> common.AgentRouters.HttpRouter
	2, // 1: common.AgentRouters.tcp_routers:type_name -> common.AgentRouters.TcpRouter
	3, // 2: common.Ping.Ping:input_type -> google.protobuf.Empty
	3, // 3: common.Ping.Ping:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
