// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proxy/proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	EventsChannel(ctx context.Context, opts ...grpc.CallOption) (Proxy_EventsChannelClient, error)
	ConnectionChannel(ctx context.Context, opts ...grpc.CallOption) (Proxy_ConnectionChannelClient, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) EventsChannel(ctx context.Context, opts ...grpc.CallOption) (Proxy_EventsChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[0], "/proxy.Proxy/EventsChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyEventsChannelClient{stream}
	return x, nil
}

type Proxy_EventsChannelClient interface {
	Send(*AgentEvent) error
	Recv() (*ProxyEvent, error)
	grpc.ClientStream
}

type proxyEventsChannelClient struct {
	grpc.ClientStream
}

func (x *proxyEventsChannelClient) Send(m *AgentEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyEventsChannelClient) Recv() (*ProxyEvent, error) {
	m := new(ProxyEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *proxyClient) ConnectionChannel(ctx context.Context, opts ...grpc.CallOption) (Proxy_ConnectionChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[1], "/proxy.Proxy/ConnectionChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyConnectionChannelClient{stream}
	return x, nil
}

type Proxy_ConnectionChannelClient interface {
	Send(*ConnectionMessage) error
	Recv() (*ConnectionMessage, error)
	grpc.ClientStream
}

type proxyConnectionChannelClient struct {
	grpc.ClientStream
}

func (x *proxyConnectionChannelClient) Send(m *ConnectionMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyConnectionChannelClient) Recv() (*ConnectionMessage, error) {
	m := new(ConnectionMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	EventsChannel(Proxy_EventsChannelServer) error
	ConnectionChannel(Proxy_ConnectionChannelServer) error
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) EventsChannel(Proxy_EventsChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method EventsChannel not implemented")
}
func (UnimplementedProxyServer) ConnectionChannel(Proxy_ConnectionChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectionChannel not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_EventsChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).EventsChannel(&proxyEventsChannelServer{stream})
}

type Proxy_EventsChannelServer interface {
	Send(*ProxyEvent) error
	Recv() (*AgentEvent, error)
	grpc.ServerStream
}

type proxyEventsChannelServer struct {
	grpc.ServerStream
}

func (x *proxyEventsChannelServer) Send(m *ProxyEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyEventsChannelServer) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Proxy_ConnectionChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).ConnectionChannel(&proxyConnectionChannelServer{stream})
}

type Proxy_ConnectionChannelServer interface {
	Send(*ConnectionMessage) error
	Recv() (*ConnectionMessage, error)
	grpc.ServerStream
}

type proxyConnectionChannelServer struct {
	grpc.ServerStream
}

func (x *proxyConnectionChannelServer) Send(m *ConnectionMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyConnectionChannelServer) Recv() (*ConnectionMessage, error) {
	m := new(ConnectionMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventsChannel",
			Handler:       _Proxy_EventsChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConnectionChannel",
			Handler:       _Proxy_ConnectionChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proxy/proxy.proto",
}
