// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proxy/proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyEventType int32

const (
	ProxyEventType_PETYPE_UNSPECIFIED    ProxyEventType = 0
	ProxyEventType_PETYPE_PING           ProxyEventType = 1
	ProxyEventType_PETYPE_OK             ProxyEventType = 2 // response
	ProxyEventType_PETYPE_ERROR          ProxyEventType = 3 // response
	ProxyEventType_PETYPE_NEW_CONNECTION ProxyEventType = 4
)

// Enum value maps for ProxyEventType.
var (
	ProxyEventType_name = map[int32]string{
		0: "PETYPE_UNSPECIFIED",
		1: "PETYPE_PING",
		2: "PETYPE_OK",
		3: "PETYPE_ERROR",
		4: "PETYPE_NEW_CONNECTION",
	}
	ProxyEventType_value = map[string]int32{
		"PETYPE_UNSPECIFIED":    0,
		"PETYPE_PING":           1,
		"PETYPE_OK":             2,
		"PETYPE_ERROR":          3,
		"PETYPE_NEW_CONNECTION": 4,
	}
)

func (x ProxyEventType) Enum() *ProxyEventType {
	p := new(ProxyEventType)
	*p = x
	return p
}

func (x ProxyEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proxy_proto_enumTypes[0].Descriptor()
}

func (ProxyEventType) Type() protoreflect.EnumType {
	return &file_proxy_proxy_proto_enumTypes[0]
}

func (x ProxyEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyEventType.Descriptor instead.
func (ProxyEventType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

type AgentEventType int32

const (
	AgentEventType_AETYPE_UNSPECIFIED AgentEventType = 0
	AgentEventType_AETYPE_PING        AgentEventType = 1
	AgentEventType_AETYPE_OK          AgentEventType = 2 // response
	AgentEventType_AETYPE_ERROR       AgentEventType = 3 // response
	AgentEventType_AETYPE_REGISTER    AgentEventType = 4
)

// Enum value maps for AgentEventType.
var (
	AgentEventType_name = map[int32]string{
		0: "AETYPE_UNSPECIFIED",
		1: "AETYPE_PING",
		2: "AETYPE_OK",
		3: "AETYPE_ERROR",
		4: "AETYPE_REGISTER",
	}
	AgentEventType_value = map[string]int32{
		"AETYPE_UNSPECIFIED": 0,
		"AETYPE_PING":        1,
		"AETYPE_OK":          2,
		"AETYPE_ERROR":       3,
		"AETYPE_REGISTER":    4,
	}
)

func (x AgentEventType) Enum() *AgentEventType {
	p := new(AgentEventType)
	*p = x
	return p
}

func (x AgentEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proxy_proto_enumTypes[1].Descriptor()
}

func (AgentEventType) Type() protoreflect.EnumType {
	return &file_proxy_proxy_proto_enumTypes[1]
}

func (x AgentEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEventType.Descriptor instead.
func (AgentEventType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

type ConnectionMessage_MessageType int32

const (
	ConnectionMessage_MSGTYPE_CHUNK    ConnectionMessage_MessageType = 0
	ConnectionMessage_MSGTYPE_METADATA ConnectionMessage_MessageType = 1
)

// Enum value maps for ConnectionMessage_MessageType.
var (
	ConnectionMessage_MessageType_name = map[int32]string{
		0: "MSGTYPE_CHUNK",
		1: "MSGTYPE_METADATA",
	}
	ConnectionMessage_MessageType_value = map[string]int32{
		"MSGTYPE_CHUNK":    0,
		"MSGTYPE_METADATA": 1,
	}
)

func (x ConnectionMessage_MessageType) Enum() *ConnectionMessage_MessageType {
	p := new(ConnectionMessage_MessageType)
	*p = x
	return p
}

func (x ConnectionMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proxy_proto_enumTypes[2].Descriptor()
}

func (ConnectionMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proxy_proxy_proto_enumTypes[2]
}

func (x ConnectionMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionMessage_MessageType.Descriptor instead.
func (ConnectionMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{2, 0}
}

type ProxyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type       ProxyEventType `protobuf:"varint,2,opt,name=type,proto3,enum=proxy.ProxyEventType" json:"type,omitempty"`
	IsResponse bool           `protobuf:"varint,3,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	// Types that are assignable to Body:
	//
	//	*ProxyEvent_Ping
	//	*ProxyEvent_Error
	//	*ProxyEvent_NewConnection_
	Body isProxyEvent_Body `protobuf_oneof:"body"`
}

func (x *ProxyEvent) Reset() {
	*x = ProxyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEvent) ProtoMessage() {}

func (x *ProxyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEvent.ProtoReflect.Descriptor instead.
func (*ProxyEvent) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyEvent) GetType() ProxyEventType {
	if x != nil {
		return x.Type
	}
	return ProxyEventType_PETYPE_UNSPECIFIED
}

func (x *ProxyEvent) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (m *ProxyEvent) GetBody() isProxyEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ProxyEvent) GetPing() *emptypb.Empty {
	if x, ok := x.GetBody().(*ProxyEvent_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *ProxyEvent) GetError() string {
	if x, ok := x.GetBody().(*ProxyEvent_Error); ok {
		return x.Error
	}
	return ""
}

func (x *ProxyEvent) GetNewConnection() *ProxyEvent_NewConnection {
	if x, ok := x.GetBody().(*ProxyEvent_NewConnection_); ok {
		return x.NewConnection
	}
	return nil
}

type isProxyEvent_Body interface {
	isProxyEvent_Body()
}

type ProxyEvent_Ping struct {
	Ping *emptypb.Empty `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type ProxyEvent_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ProxyEvent_NewConnection_ struct {
	NewConnection *ProxyEvent_NewConnection `protobuf:"bytes,6,opt,name=new_connection,json=newConnection,proto3,oneof"`
}

func (*ProxyEvent_Ping) isProxyEvent_Body() {}

func (*ProxyEvent_Error) isProxyEvent_Body() {}

func (*ProxyEvent_NewConnection_) isProxyEvent_Body() {}

type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type       AgentEventType `protobuf:"varint,2,opt,name=type,proto3,enum=proxy.AgentEventType" json:"type,omitempty"`
	IsResponse bool           `protobuf:"varint,3,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	// Types that are assignable to Body:
	//
	//	*AgentEvent_Ping
	//	*AgentEvent_Error
	//	*AgentEvent_AgentInfo_
	Body isAgentEvent_Body `protobuf_oneof:"body"`
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentEvent) GetType() AgentEventType {
	if x != nil {
		return x.Type
	}
	return AgentEventType_AETYPE_UNSPECIFIED
}

func (x *AgentEvent) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (m *AgentEvent) GetBody() isAgentEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *AgentEvent) GetPing() *emptypb.Empty {
	if x, ok := x.GetBody().(*AgentEvent_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *AgentEvent) GetError() string {
	if x, ok := x.GetBody().(*AgentEvent_Error); ok {
		return x.Error
	}
	return ""
}

func (x *AgentEvent) GetAgentInfo() *AgentEvent_AgentInfo {
	if x, ok := x.GetBody().(*AgentEvent_AgentInfo_); ok {
		return x.AgentInfo
	}
	return nil
}

type isAgentEvent_Body interface {
	isAgentEvent_Body()
}

type AgentEvent_Ping struct {
	Ping *emptypb.Empty `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type AgentEvent_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type AgentEvent_AgentInfo_ struct {
	AgentInfo *AgentEvent_AgentInfo `protobuf:"bytes,6,opt,name=agent_info,json=agentInfo,proto3,oneof"`
}

func (*AgentEvent_Ping) isAgentEvent_Body() {}

func (*AgentEvent_Error) isAgentEvent_Body() {}

func (*AgentEvent_AgentInfo_) isAgentEvent_Body() {}

type ConnectionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ConnectionMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=proxy.ConnectionMessage_MessageType" json:"type,omitempty"`
	// Types that are assignable to Body:
	//
	//	*ConnectionMessage_Chunk
	//	*ConnectionMessage_Metadata_
	Body isConnectionMessage_Body `protobuf_oneof:"body"`
}

func (x *ConnectionMessage) Reset() {
	*x = ConnectionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage) ProtoMessage() {}

func (x *ConnectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage.ProtoReflect.Descriptor instead.
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionMessage) GetType() ConnectionMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return ConnectionMessage_MSGTYPE_CHUNK
}

func (m *ConnectionMessage) GetBody() isConnectionMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ConnectionMessage) GetChunk() []byte {
	if x, ok := x.GetBody().(*ConnectionMessage_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *ConnectionMessage) GetMetadata() *ConnectionMessage_Metadata {
	if x, ok := x.GetBody().(*ConnectionMessage_Metadata_); ok {
		return x.Metadata
	}
	return nil
}

type isConnectionMessage_Body interface {
	isConnectionMessage_Body()
}

type ConnectionMessage_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ConnectionMessage_Metadata_ struct {
	Metadata *ConnectionMessage_Metadata `protobuf:"bytes,3,opt,name=metadata,proto3,oneof"`
}

func (*ConnectionMessage_Chunk) isConnectionMessage_Body() {}

func (*ConnectionMessage_Metadata_) isConnectionMessage_Body() {}

type ProxyEvent_NewConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid       string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ConnectTo string `protobuf:"bytes,2,opt,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
}

func (x *ProxyEvent_NewConnection) Reset() {
	*x = ProxyEvent_NewConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyEvent_NewConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEvent_NewConnection) ProtoMessage() {}

func (x *ProxyEvent_NewConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEvent_NewConnection.ProtoReflect.Descriptor instead.
func (*ProxyEvent_NewConnection) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProxyEvent_NewConnection) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ProxyEvent_NewConnection) GetConnectTo() string {
	if x != nil {
		return x.ConnectTo
	}
	return ""
}

type AgentEvent_AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AgentEvent_AgentInfo) Reset() {
	*x = AgentEvent_AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent_AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent_AgentInfo) ProtoMessage() {}

func (x *AgentEvent_AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent_AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentEvent_AgentInfo) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AgentEvent_AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConnectionMessage_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *ConnectionMessage_Metadata) Reset() {
	*x = ConnectionMessage_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionMessage_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage_Metadata) ProtoMessage() {}

func (x *ConnectionMessage_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage_Metadata.ProtoReflect.Descriptor instead.
func (*ConnectionMessage_Metadata) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ConnectionMessage_Metadata) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

var File_proxy_proxy_proto protoreflect.FileDescriptor

var file_proxy_proxy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x02, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x48, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x40, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x54, 0x6f, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x95, 0x02, 0x0a,
	0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3c, 0x0a,
	0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00,
	0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1f, 0x0a, 0x09, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x84, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x3f, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1c, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x53,
	0x47, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x4d, 0x53, 0x47, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x44, 0x41, 0x54,
	0x41, 0x10, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0x75, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x12, 0x50, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x45, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x04, 0x2a, 0x6f, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x13,
	0x0a, 0x0f, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45,
	0x52, 0x10, 0x04, 0x32, 0x8f, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x39, 0x0a,
	0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6b, 0x76, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proxy_proxy_proto_rawDescOnce sync.Once
	file_proxy_proxy_proto_rawDescData = file_proxy_proxy_proto_rawDesc
)

func file_proxy_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_proxy_proto_rawDescData)
	})
	return file_proxy_proxy_proto_rawDescData
}

var file_proxy_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proxy_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proxy_proxy_proto_goTypes = []interface{}{
	(ProxyEventType)(0),                // 0: proxy.ProxyEventType
	(AgentEventType)(0),                // 1: proxy.AgentEventType
	(ConnectionMessage_MessageType)(0), // 2: proxy.ConnectionMessage.MessageType
	(*ProxyEvent)(nil),                 // 3: proxy.ProxyEvent
	(*AgentEvent)(nil),                 // 4: proxy.AgentEvent
	(*ConnectionMessage)(nil),          // 5: proxy.ConnectionMessage
	(*ProxyEvent_NewConnection)(nil),   // 6: proxy.ProxyEvent.NewConnection
	(*AgentEvent_AgentInfo)(nil),       // 7: proxy.AgentEvent.AgentInfo
	(*ConnectionMessage_Metadata)(nil), // 8: proxy.ConnectionMessage.Metadata
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_proxy_proxy_proto_depIdxs = []int32{
	0,  // 0: proxy.ProxyEvent.type:type_name -> proxy.ProxyEventType
	9,  // 1: proxy.ProxyEvent.ping:type_name -> google.protobuf.Empty
	6,  // 2: proxy.ProxyEvent.new_connection:type_name -> proxy.ProxyEvent.NewConnection
	1,  // 3: proxy.AgentEvent.type:type_name -> proxy.AgentEventType
	9,  // 4: proxy.AgentEvent.ping:type_name -> google.protobuf.Empty
	7,  // 5: proxy.AgentEvent.agent_info:type_name -> proxy.AgentEvent.AgentInfo
	2,  // 6: proxy.ConnectionMessage.type:type_name -> proxy.ConnectionMessage.MessageType
	8,  // 7: proxy.ConnectionMessage.metadata:type_name -> proxy.ConnectionMessage.Metadata
	4,  // 8: proxy.Proxy.EventsChannel:input_type -> proxy.AgentEvent
	5,  // 9: proxy.Proxy.ConnectionChannel:input_type -> proxy.ConnectionMessage
	3,  // 10: proxy.Proxy.EventsChannel:output_type -> proxy.ProxyEvent
	5,  // 11: proxy.Proxy.ConnectionChannel:output_type -> proxy.ConnectionMessage
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proxy_proxy_proto_init() }
func file_proxy_proxy_proto_init() {
	if File_proxy_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxy_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyEvent_NewConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent_AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionMessage_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proxy_proxy_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProxyEvent_Ping)(nil),
		(*ProxyEvent_Error)(nil),
		(*ProxyEvent_NewConnection_)(nil),
	}
	file_proxy_proxy_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AgentEvent_Ping)(nil),
		(*AgentEvent_Error)(nil),
		(*AgentEvent_AgentInfo_)(nil),
	}
	file_proxy_proxy_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ConnectionMessage_Chunk)(nil),
		(*ConnectionMessage_Metadata_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxy_proxy_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proxy_proto = out.File
	file_proxy_proxy_proto_rawDesc = nil
	file_proxy_proxy_proto_goTypes = nil
	file_proxy_proxy_proto_depIdxs = nil
}
