// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: proxyagent/agent.proto

package proxyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConnectionMessage_Chunk
	//	*ConnectionMessage_Header_
	//	*ConnectionMessage_HeaderResponse_
	Body          isConnectionMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage) Reset() {
	*x = ConnectionMessage{}
	mi := &file_proxyagent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage) ProtoMessage() {}

func (x *ConnectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage.ProtoReflect.Descriptor instead.
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionMessage) GetBody() isConnectionMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConnectionMessage) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ConnectionMessage) GetHeader() *ConnectionMessage_Header {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_Header_); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ConnectionMessage) GetHeaderResponse() *ConnectionMessage_HeaderResponse {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_HeaderResponse_); ok {
			return x.HeaderResponse
		}
	}
	return nil
}

type isConnectionMessage_Body interface {
	isConnectionMessage_Body()
}

type ConnectionMessage_Chunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type ConnectionMessage_Header_ struct {
	Header *ConnectionMessage_Header `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type ConnectionMessage_HeaderResponse_ struct {
	HeaderResponse *ConnectionMessage_HeaderResponse `protobuf:"bytes,3,opt,name=header_response,json=headerResponse,proto3,oneof"`
}

func (*ConnectionMessage_Chunk) isConnectionMessage_Body() {}

func (*ConnectionMessage_Header_) isConnectionMessage_Body() {}

func (*ConnectionMessage_HeaderResponse_) isConnectionMessage_Body() {}

type ConnectionMessage_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ConnectTo     string                 `protobuf:"bytes,2,opt,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage_Header) Reset() {
	*x = ConnectionMessage_Header{}
	mi := &file_proxyagent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage_Header) ProtoMessage() {}

func (x *ConnectionMessage_Header) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage_Header.ProtoReflect.Descriptor instead.
func (*ConnectionMessage_Header) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectionMessage_Header) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ConnectionMessage_Header) GetConnectTo() string {
	if x != nil {
		return x.ConnectTo
	}
	return ""
}

type ConnectionMessage_HeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage_HeaderResponse) Reset() {
	*x = ConnectionMessage_HeaderResponse{}
	mi := &file_proxyagent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage_HeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage_HeaderResponse) ProtoMessage() {}

func (x *ConnectionMessage_HeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage_HeaderResponse.ProtoReflect.Descriptor instead.
func (*ConnectionMessage_HeaderResponse) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConnectionMessage_HeaderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proxyagent_agent_proto protoreflect.FileDescriptor

var file_proxyagent_agent_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x22, 0xaf, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x3e, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x57, 0x0a, 0x0f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x39, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x1a, 0x26, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x66, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x46,
	0x6f, 0x72, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x55, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6b,
	0x76, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proxyagent_agent_proto_rawDescOnce sync.Once
	file_proxyagent_agent_proto_rawDescData []byte
)

func file_proxyagent_agent_proto_rawDescGZIP() []byte {
	file_proxyagent_agent_proto_rawDescOnce.Do(func() {
		file_proxyagent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxyagent_agent_proto_rawDesc), len(file_proxyagent_agent_proto_rawDesc)))
	})
	return file_proxyagent_agent_proto_rawDescData
}

var file_proxyagent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxyagent_agent_proto_goTypes = []any{
	(*ConnectionMessage)(nil),                // 0: proxyagent.ConnectionMessage
	(*ConnectionMessage_Header)(nil),         // 1: proxyagent.ConnectionMessage.Header
	(*ConnectionMessage_HeaderResponse)(nil), // 2: proxyagent.ConnectionMessage.HeaderResponse
}
var file_proxyagent_agent_proto_depIdxs = []int32{
	1, // 0: proxyagent.ConnectionMessage.header:type_name -> proxyagent.ConnectionMessage.Header
	2, // 1: proxyagent.ConnectionMessage.header_response:type_name -> proxyagent.ConnectionMessage.HeaderResponse
	0, // 2: proxyagent.AgentForProxy.ConnectionChannel:input_type -> proxyagent.ConnectionMessage
	0, // 3: proxyagent.AgentForProxy.ConnectionChannel:output_type -> proxyagent.ConnectionMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxyagent_agent_proto_init() }
func file_proxyagent_agent_proto_init() {
	if File_proxyagent_agent_proto != nil {
		return
	}
	file_proxyagent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectionMessage_Chunk)(nil),
		(*ConnectionMessage_Header_)(nil),
		(*ConnectionMessage_HeaderResponse_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxyagent_agent_proto_rawDesc), len(file_proxyagent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxyagent_agent_proto_goTypes,
		DependencyIndexes: file_proxyagent_agent_proto_depIdxs,
		MessageInfos:      file_proxyagent_agent_proto_msgTypes,
	}.Build()
	File_proxyagent_agent_proto = out.File
	file_proxyagent_agent_proto_goTypes = nil
	file_proxyagent_agent_proto_depIdxs = nil
}
