// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proxyagent/agent.proto

package proxyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConnectionMessage_Chunk
	//	*ConnectionMessage_Header_
	//	*ConnectionMessage_HeaderResponse_
	Body          isConnectionMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage) Reset() {
	*x = ConnectionMessage{}
	mi := &file_proxyagent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage) ProtoMessage() {}

func (x *ConnectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage.ProtoReflect.Descriptor instead.
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionMessage) GetBody() isConnectionMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConnectionMessage) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ConnectionMessage) GetHeader() *ConnectionMessage_Header {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_Header_); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ConnectionMessage) GetHeaderResponse() *ConnectionMessage_HeaderResponse {
	if x != nil {
		if x, ok := x.Body.(*ConnectionMessage_HeaderResponse_); ok {
			return x.HeaderResponse
		}
	}
	return nil
}

type isConnectionMessage_Body interface {
	isConnectionMessage_Body()
}

type ConnectionMessage_Chunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type ConnectionMessage_Header_ struct {
	Header *ConnectionMessage_Header `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type ConnectionMessage_HeaderResponse_ struct {
	HeaderResponse *ConnectionMessage_HeaderResponse `protobuf:"bytes,3,opt,name=header_response,json=headerResponse,proto3,oneof"`
}

func (*ConnectionMessage_Chunk) isConnectionMessage_Body() {}

func (*ConnectionMessage_Header_) isConnectionMessage_Body() {}

func (*ConnectionMessage_HeaderResponse_) isConnectionMessage_Body() {}

type ConnectionMessage_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	ConnectTo     string                 `protobuf:"bytes,2,opt,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage_Header) Reset() {
	*x = ConnectionMessage_Header{}
	mi := &file_proxyagent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage_Header) ProtoMessage() {}

func (x *ConnectionMessage_Header) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage_Header.ProtoReflect.Descriptor instead.
func (*ConnectionMessage_Header) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectionMessage_Header) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ConnectionMessage_Header) GetConnectTo() string {
	if x != nil {
		return x.ConnectTo
	}
	return ""
}

type ConnectionMessage_HeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMessage_HeaderResponse) Reset() {
	*x = ConnectionMessage_HeaderResponse{}
	mi := &file_proxyagent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMessage_HeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage_HeaderResponse) ProtoMessage() {}

func (x *ConnectionMessage_HeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxyagent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage_HeaderResponse.ProtoReflect.Descriptor instead.
func (*ConnectionMessage_HeaderResponse) Descriptor() ([]byte, []int) {
	return file_proxyagent_agent_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConnectionMessage_HeaderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proxyagent_agent_proto protoreflect.FileDescriptor

const file_proxyagent_agent_proto_rawDesc = "" +
	"\n" +
	"\x16proxyagent/agent.proto\x12\n" +
	"proxyagent\"\xaf\x02\n" +
	"\x11ConnectionMessage\x12\x16\n" +
	"\x05chunk\x18\x01 \x01(\fH\x00R\x05chunk\x12>\n" +
	"\x06header\x18\x02 \x01(\v2$.proxyagent.ConnectionMessage.HeaderH\x00R\x06header\x12W\n" +
	"\x0fheader_response\x18\x03 \x01(\v2,.proxyagent.ConnectionMessage.HeaderResponseH\x00R\x0eheaderResponse\x1a9\n" +
	"\x06Header\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x1d\n" +
	"\n" +
	"connect_to\x18\x02 \x01(\tR\tconnectTo\x1a&\n" +
	"\x0eHeaderResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB\x06\n" +
	"\x04body2f\n" +
	"\rAgentForProxy\x12U\n" +
	"\x11ConnectionChannel\x12\x1d.proxyagent.ConnectionMessage\x1a\x1d.proxyagent.ConnectionMessage(\x010\x01B-Z+github.com/pikvm/cloud-api/proto/proxyagentb\x06proto3"

var (
	file_proxyagent_agent_proto_rawDescOnce sync.Once
	file_proxyagent_agent_proto_rawDescData []byte
)

func file_proxyagent_agent_proto_rawDescGZIP() []byte {
	file_proxyagent_agent_proto_rawDescOnce.Do(func() {
		file_proxyagent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxyagent_agent_proto_rawDesc), len(file_proxyagent_agent_proto_rawDesc)))
	})
	return file_proxyagent_agent_proto_rawDescData
}

var file_proxyagent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxyagent_agent_proto_goTypes = []any{
	(*ConnectionMessage)(nil),                // 0: proxyagent.ConnectionMessage
	(*ConnectionMessage_Header)(nil),         // 1: proxyagent.ConnectionMessage.Header
	(*ConnectionMessage_HeaderResponse)(nil), // 2: proxyagent.ConnectionMessage.HeaderResponse
}
var file_proxyagent_agent_proto_depIdxs = []int32{
	1, // 0: proxyagent.ConnectionMessage.header:type_name -> proxyagent.ConnectionMessage.Header
	2, // 1: proxyagent.ConnectionMessage.header_response:type_name -> proxyagent.ConnectionMessage.HeaderResponse
	0, // 2: proxyagent.AgentForProxy.ConnectionChannel:input_type -> proxyagent.ConnectionMessage
	0, // 3: proxyagent.AgentForProxy.ConnectionChannel:output_type -> proxyagent.ConnectionMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxyagent_agent_proto_init() }
func file_proxyagent_agent_proto_init() {
	if File_proxyagent_agent_proto != nil {
		return
	}
	file_proxyagent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectionMessage_Chunk)(nil),
		(*ConnectionMessage_Header_)(nil),
		(*ConnectionMessage_HeaderResponse_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxyagent_agent_proto_rawDesc), len(file_proxyagent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxyagent_agent_proto_goTypes,
		DependencyIndexes: file_proxyagent_agent_proto_depIdxs,
		MessageInfos:      file_proxyagent_agent_proto_msgTypes,
	}.Build()
	File_proxyagent_agent_proto = out.File
	file_proxyagent_agent_proto_goTypes = nil
	file_proxyagent_agent_proto_depIdxs = nil
}
