// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proxyagent/proxy.proto

package proxyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proxyagent_proxy_proto protoreflect.FileDescriptor

const file_proxyagent_proxy_proto_rawDesc = "" +
	"\n" +
	"\x16proxyagent/proxy.proto\x12\n" +
	"proxyagent2\x0f\n" +
	"\rProxyForAgentB-Z+github.com/pikvm/cloud-api/proto/proxyagentb\x06proto3"

var file_proxyagent_proxy_proto_goTypes = []any{}
var file_proxyagent_proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxyagent_proxy_proto_init() }
func file_proxyagent_proxy_proto_init() {
	if File_proxyagent_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxyagent_proxy_proto_rawDesc), len(file_proxyagent_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxyagent_proxy_proto_goTypes,
		DependencyIndexes: file_proxyagent_proxy_proto_depIdxs,
	}.Build()
	File_proxyagent_proxy_proto = out.File
	file_proxyagent_proxy_proto_goTypes = nil
	file_proxyagent_proxy_proto_depIdxs = nil
}
