// Code generated by protoc-gen-go-xrpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-xrpc v1.1.0
// - protoc             v5.29.2
// source: proxyagent/proxy.proto

package proxyagent

import (
	xrpc "github.com/xornet-sl/go-xrpc/xrpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires go-xrpc v1.0.0 or later.
const _ = xrpc.SupportPackageIsVersion1

// ProxyForAgentClient is the client API for ProxyForAgent service.
type ProxyForAgentClient interface {
}

type proxyForAgentClient struct {
	cc xrpc.InvokableConnection
}

func NewProxyForAgentClient(cc xrpc.InvokableConnection) ProxyForAgentClient {
	return &proxyForAgentClient{cc}
}

// ProxyForAgentServer is the server API for ProxyForAgent service.
// All implementations must embed UnimplementedProxyForAgentServer
// for forward compatibility
type ProxyForAgentServer interface {
	mustEmbedUnimplementedProxyForAgentServer()
}

// UnimplementedProxyForAgentServer must be embedded to have forward compatible implementations.
type UnimplementedProxyForAgentServer struct {
}

func (UnimplementedProxyForAgentServer) mustEmbedUnimplementedProxyForAgentServer() {}

func RegisterProxyForAgentServer(s xrpc.ServiceRegistrar, srv ProxyForAgentServer) {
	s.RegisterService(&ProxyForAgent_ServiceDesc, srv)
}

// ProxyForAgent_ServiceDesc is the xrpc.ServiceDesc for ProxyForAgent service.
// It's only intended for direct use with xrpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyForAgent_ServiceDesc = xrpc.ServiceDesc{
	ServiceName: "proxyagent.ProxyForAgent",
	HandlerType: (*ProxyForAgentServer)(nil),
	Methods:     map[string]xrpc.MethodHandler{},
	Streams:     map[string]xrpc.StreamDesc{},
}
