// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: hive_for_agent/hive_for_agent.proto

package hive_for_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiveEventType int32

const (
	HiveEventType_HETYPE_UNSPECIFIED HiveEventType = 0
	HiveEventType_HETYPE_PING        HiveEventType = 1
	HiveEventType_HETYPE_OK          HiveEventType = 2 // response
	HiveEventType_HETYPE_ERROR       HiveEventType = 3 // response
)

// Enum value maps for HiveEventType.
var (
	HiveEventType_name = map[int32]string{
		0: "HETYPE_UNSPECIFIED",
		1: "HETYPE_PING",
		2: "HETYPE_OK",
		3: "HETYPE_ERROR",
	}
	HiveEventType_value = map[string]int32{
		"HETYPE_UNSPECIFIED": 0,
		"HETYPE_PING":        1,
		"HETYPE_OK":          2,
		"HETYPE_ERROR":       3,
	}
)

func (x HiveEventType) Enum() *HiveEventType {
	p := new(HiveEventType)
	*p = x
	return p
}

func (x HiveEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HiveEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_hive_for_agent_hive_for_agent_proto_enumTypes[0].Descriptor()
}

func (HiveEventType) Type() protoreflect.EnumType {
	return &file_hive_for_agent_hive_for_agent_proto_enumTypes[0]
}

func (x HiveEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HiveEventType.Descriptor instead.
func (HiveEventType) EnumDescriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{0}
}

type AgentEventType int32

const (
	AgentEventType_AETYPE_UNSPECIFIED AgentEventType = 0
	AgentEventType_AETYPE_PING        AgentEventType = 1
	AgentEventType_AETYPE_OK          AgentEventType = 2 // response
	AgentEventType_AETYPE_ERROR       AgentEventType = 3 //response
	AgentEventType_AETYPE_REGISTER    AgentEventType = 4
)

// Enum value maps for AgentEventType.
var (
	AgentEventType_name = map[int32]string{
		0: "AETYPE_UNSPECIFIED",
		1: "AETYPE_PING",
		2: "AETYPE_OK",
		3: "AETYPE_ERROR",
		4: "AETYPE_REGISTER",
	}
	AgentEventType_value = map[string]int32{
		"AETYPE_UNSPECIFIED": 0,
		"AETYPE_PING":        1,
		"AETYPE_OK":          2,
		"AETYPE_ERROR":       3,
		"AETYPE_REGISTER":    4,
	}
)

func (x AgentEventType) Enum() *AgentEventType {
	p := new(AgentEventType)
	*p = x
	return p
}

func (x AgentEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_hive_for_agent_hive_for_agent_proto_enumTypes[1].Descriptor()
}

func (AgentEventType) Type() protoreflect.EnumType {
	return &file_hive_for_agent_hive_for_agent_proto_enumTypes[1]
}

func (x AgentEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEventType.Descriptor instead.
func (AgentEventType) EnumDescriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{1}
}

type HiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type       HiveEventType `protobuf:"varint,2,opt,name=type,proto3,enum=hive_for_agent.HiveEventType" json:"type,omitempty"`
	IsResponse bool          `protobuf:"varint,3,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	// Types that are assignable to Body:
	//
	//	*HiveEvent_Ping
	//	*HiveEvent_Error
	Body isHiveEvent_Body `protobuf_oneof:"body"`
}

func (x *HiveEvent) Reset() {
	*x = HiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiveEvent) ProtoMessage() {}

func (x *HiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiveEvent.ProtoReflect.Descriptor instead.
func (*HiveEvent) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HiveEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HiveEvent) GetType() HiveEventType {
	if x != nil {
		return x.Type
	}
	return HiveEventType_HETYPE_UNSPECIFIED
}

func (x *HiveEvent) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (m *HiveEvent) GetBody() isHiveEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *HiveEvent) GetPing() *emptypb.Empty {
	if x, ok := x.GetBody().(*HiveEvent_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *HiveEvent) GetError() string {
	if x, ok := x.GetBody().(*HiveEvent_Error); ok {
		return x.Error
	}
	return ""
}

type isHiveEvent_Body interface {
	isHiveEvent_Body()
}

type HiveEvent_Ping struct {
	Ping *emptypb.Empty `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type HiveEvent_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*HiveEvent_Ping) isHiveEvent_Body() {}

func (*HiveEvent_Error) isHiveEvent_Body() {}

type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type       AgentEventType `protobuf:"varint,2,opt,name=type,proto3,enum=hive_for_agent.AgentEventType" json:"type,omitempty"`
	IsResponse bool           `protobuf:"varint,3,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	// Types that are assignable to Body:
	//
	//	*AgentEvent_Ping
	//	*AgentEvent_Error
	//	*AgentEvent_AgentInfo_
	Body isAgentEvent_Body `protobuf_oneof:"body"`
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentEvent) GetType() AgentEventType {
	if x != nil {
		return x.Type
	}
	return AgentEventType_AETYPE_UNSPECIFIED
}

func (x *AgentEvent) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (m *AgentEvent) GetBody() isAgentEvent_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *AgentEvent) GetPing() *emptypb.Empty {
	if x, ok := x.GetBody().(*AgentEvent_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *AgentEvent) GetError() string {
	if x, ok := x.GetBody().(*AgentEvent_Error); ok {
		return x.Error
	}
	return ""
}

func (x *AgentEvent) GetAgentInfo() *AgentEvent_AgentInfo {
	if x, ok := x.GetBody().(*AgentEvent_AgentInfo_); ok {
		return x.AgentInfo
	}
	return nil
}

type isAgentEvent_Body interface {
	isAgentEvent_Body()
}

type AgentEvent_Ping struct {
	Ping *emptypb.Empty `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type AgentEvent_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type AgentEvent_AgentInfo_ struct {
	AgentInfo *AgentEvent_AgentInfo `protobuf:"bytes,6,opt,name=agent_info,json=agentInfo,proto3,oneof"`
}

func (*AgentEvent_Ping) isAgentEvent_Body() {}

func (*AgentEvent_Error) isAgentEvent_Body() {}

func (*AgentEvent_AgentInfo_) isAgentEvent_Body() {}

type AvailableProxies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableProxies []*AvailableProxies_ProxyInfo `protobuf:"bytes,1,rep,name=available_proxies,json=availableProxies,proto3" json:"available_proxies,omitempty"`
}

func (x *AvailableProxies) Reset() {
	*x = AvailableProxies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableProxies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableProxies) ProtoMessage() {}

func (x *AvailableProxies) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableProxies.ProtoReflect.Descriptor instead.
func (*AvailableProxies) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableProxies) GetAvailableProxies() []*AvailableProxies_ProxyInfo {
	if x != nil {
		return x.AvailableProxies
	}
	return nil
}

type CertbotDomainName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainName string `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	Txt        string `protobuf:"bytes,2,opt,name=txt,proto3" json:"txt,omitempty"`
}

func (x *CertbotDomainName) Reset() {
	*x = CertbotDomainName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertbotDomainName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertbotDomainName) ProtoMessage() {}

func (x *CertbotDomainName) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertbotDomainName.ProtoReflect.Descriptor instead.
func (*CertbotDomainName) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CertbotDomainName) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *CertbotDomainName) GetTxt() string {
	if x != nil {
		return x.Txt
	}
	return ""
}

type AgentEvent_AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AgentEvent_AgentInfo) Reset() {
	*x = AgentEvent_AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent_AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent_AgentInfo) ProtoMessage() {}

func (x *AgentEvent_AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent_AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentEvent_AgentInfo) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AgentEvent_AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentEvent_AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AvailableProxies_ProxyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyEndpoint string `protobuf:"bytes,1,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
}

func (x *AvailableProxies_ProxyInfo) Reset() {
	*x = AvailableProxies_ProxyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableProxies_ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableProxies_ProxyInfo) ProtoMessage() {}

func (x *AvailableProxies_ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hive_for_agent_hive_for_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableProxies_ProxyInfo.ProtoReflect.Descriptor instead.
func (*AvailableProxies_ProxyInfo) Descriptor() ([]byte, []int) {
	return file_hive_for_agent_hive_for_agent_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AvailableProxies_ProxyInfo) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

var File_hive_for_agent_hive_for_agent_proto protoreflect.FileDescriptor

var file_hive_for_agent_hive_for_agent_proto_rawDesc = []byte{
	0x0a, 0x23, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x09, 0x48, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x48, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0xc1, 0x02, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x45, 0x0a, 0x0a,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x39, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x11, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f,
	0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x78, 0x69, 0x65, 0x73, 0x1a, 0x32, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x11, 0x43, 0x65, 0x72, 0x74,
	0x62, 0x6f, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x78, 0x74,
	0x2a, 0x59, 0x0a, 0x0d, 0x48, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x12, 0x48, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x45, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x45, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x2a, 0x6f, 0x0a, 0x0e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x12, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x45, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x45, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x04, 0x32, 0xfa, 0x02, 0x0a,
	0x0c, 0x48, 0x69, 0x76, 0x65, 0x46, 0x6f, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a,
	0x09, 0x41, 0x75, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x68, 0x69,
	0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0a, 0x43, 0x65, 0x72, 0x74, 0x62,
	0x6f, 0x74, 0x41, 0x64, 0x64, 0x12, 0x21, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x62, 0x6f, 0x74, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x47, 0x0a, 0x0a, 0x43, 0x65, 0x72, 0x74, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x6c, 0x12, 0x21,
	0x2e, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x43, 0x65, 0x72, 0x74, 0x62, 0x6f, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6b, 0x76, 0x6d, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hive_for_agent_hive_for_agent_proto_rawDescOnce sync.Once
	file_hive_for_agent_hive_for_agent_proto_rawDescData = file_hive_for_agent_hive_for_agent_proto_rawDesc
)

func file_hive_for_agent_hive_for_agent_proto_rawDescGZIP() []byte {
	file_hive_for_agent_hive_for_agent_proto_rawDescOnce.Do(func() {
		file_hive_for_agent_hive_for_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_hive_for_agent_hive_for_agent_proto_rawDescData)
	})
	return file_hive_for_agent_hive_for_agent_proto_rawDescData
}

var file_hive_for_agent_hive_for_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hive_for_agent_hive_for_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hive_for_agent_hive_for_agent_proto_goTypes = []interface{}{
	(HiveEventType)(0),                 // 0: hive_for_agent.HiveEventType
	(AgentEventType)(0),                // 1: hive_for_agent.AgentEventType
	(*HiveEvent)(nil),                  // 2: hive_for_agent.HiveEvent
	(*AgentEvent)(nil),                 // 3: hive_for_agent.AgentEvent
	(*AvailableProxies)(nil),           // 4: hive_for_agent.AvailableProxies
	(*CertbotDomainName)(nil),          // 5: hive_for_agent.CertbotDomainName
	(*AgentEvent_AgentInfo)(nil),       // 6: hive_for_agent.AgentEvent.AgentInfo
	(*AvailableProxies_ProxyInfo)(nil), // 7: hive_for_agent.AvailableProxies.ProxyInfo
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_hive_for_agent_hive_for_agent_proto_depIdxs = []int32{
	0,  // 0: hive_for_agent.HiveEvent.type:type_name -> hive_for_agent.HiveEventType
	8,  // 1: hive_for_agent.HiveEvent.ping:type_name -> google.protobuf.Empty
	1,  // 2: hive_for_agent.AgentEvent.type:type_name -> hive_for_agent.AgentEventType
	8,  // 3: hive_for_agent.AgentEvent.ping:type_name -> google.protobuf.Empty
	6,  // 4: hive_for_agent.AgentEvent.agent_info:type_name -> hive_for_agent.AgentEvent.AgentInfo
	7,  // 5: hive_for_agent.AvailableProxies.available_proxies:type_name -> hive_for_agent.AvailableProxies.ProxyInfo
	8,  // 6: hive_for_agent.HiveForAgent.AuthCheck:input_type -> google.protobuf.Empty
	3,  // 7: hive_for_agent.HiveForAgent.EventsChannel:input_type -> hive_for_agent.AgentEvent
	8,  // 8: hive_for_agent.HiveForAgent.GetAvailableProxies:input_type -> google.protobuf.Empty
	5,  // 9: hive_for_agent.HiveForAgent.CertbotAdd:input_type -> hive_for_agent.CertbotDomainName
	5,  // 10: hive_for_agent.HiveForAgent.CertbotDel:input_type -> hive_for_agent.CertbotDomainName
	8,  // 11: hive_for_agent.HiveForAgent.AuthCheck:output_type -> google.protobuf.Empty
	2,  // 12: hive_for_agent.HiveForAgent.EventsChannel:output_type -> hive_for_agent.HiveEvent
	4,  // 13: hive_for_agent.HiveForAgent.GetAvailableProxies:output_type -> hive_for_agent.AvailableProxies
	8,  // 14: hive_for_agent.HiveForAgent.CertbotAdd:output_type -> google.protobuf.Empty
	8,  // 15: hive_for_agent.HiveForAgent.CertbotDel:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_hive_for_agent_hive_for_agent_proto_init() }
func file_hive_for_agent_hive_for_agent_proto_init() {
	if File_hive_for_agent_hive_for_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hive_for_agent_hive_for_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hive_for_agent_hive_for_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hive_for_agent_hive_for_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableProxies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hive_for_agent_hive_for_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertbotDomainName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hive_for_agent_hive_for_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent_AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hive_for_agent_hive_for_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableProxies_ProxyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hive_for_agent_hive_for_agent_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HiveEvent_Ping)(nil),
		(*HiveEvent_Error)(nil),
	}
	file_hive_for_agent_hive_for_agent_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AgentEvent_Ping)(nil),
		(*AgentEvent_Error)(nil),
		(*AgentEvent_AgentInfo_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hive_for_agent_hive_for_agent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hive_for_agent_hive_for_agent_proto_goTypes,
		DependencyIndexes: file_hive_for_agent_hive_for_agent_proto_depIdxs,
		EnumInfos:         file_hive_for_agent_hive_for_agent_proto_enumTypes,
		MessageInfos:      file_hive_for_agent_hive_for_agent_proto_msgTypes,
	}.Build()
	File_hive_for_agent_hive_for_agent_proto = out.File
	file_hive_for_agent_hive_for_agent_proto_rawDesc = nil
	file_hive_for_agent_hive_for_agent_proto_goTypes = nil
	file_hive_for_agent_hive_for_agent_proto_depIdxs = nil
}
