// Code generated by protoc-gen-go-xrpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-xrpc v1.1.0
// - protoc             v5.29.2
// source: hiveagent/agent.proto

package hiveagent

import (
	xrpc "github.com/xornet-sl/go-xrpc/xrpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires go-xrpc v1.0.0 or later.
const _ = xrpc.SupportPackageIsVersion1

// AgentForHiveClient is the client API for AgentForHive service.
type AgentForHiveClient interface {
}

type agentForHiveClient struct {
	cc xrpc.InvokableConnection
}

func NewAgentForHiveClient(cc xrpc.InvokableConnection) AgentForHiveClient {
	return &agentForHiveClient{cc}
}

// AgentForHiveServer is the server API for AgentForHive service.
// All implementations must embed UnimplementedAgentForHiveServer
// for forward compatibility
type AgentForHiveServer interface {
	mustEmbedUnimplementedAgentForHiveServer()
}

// UnimplementedAgentForHiveServer must be embedded to have forward compatible implementations.
type UnimplementedAgentForHiveServer struct {
}

func (UnimplementedAgentForHiveServer) mustEmbedUnimplementedAgentForHiveServer() {}

func RegisterAgentForHiveServer(s xrpc.ServiceRegistrar, srv AgentForHiveServer) {
	s.RegisterService(&AgentForHive_ServiceDesc, srv)
}

// AgentForHive_ServiceDesc is the xrpc.ServiceDesc for AgentForHive service.
// It's only intended for direct use with xrpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentForHive_ServiceDesc = xrpc.ServiceDesc{
	ServiceName: "hiveagent.AgentForHive",
	HandlerType: (*AgentForHiveServer)(nil),
	Methods:     map[string]xrpc.MethodHandler{},
	Streams:     map[string]xrpc.StreamDesc{},
}
