// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: hiveagent/hive.proto

package hiveagent

import (
	common "github.com/pikvm/cloud-api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_hiveagent_hive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_hiveagent_hive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_hiveagent_hive_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Routers       *common.AgentRouters   `protobuf:"bytes,3,opt,name=routers,proto3" json:"routers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_hiveagent_hive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hiveagent_hive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_hiveagent_hive_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AgentInfo) GetRouters() *common.AgentRouters {
	if x != nil {
		return x.Routers
	}
	return nil
}

type AvailableProxies struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	AvailableProxies []*AvailableProxies_ProxyInfo `protobuf:"bytes,1,rep,name=available_proxies,json=availableProxies,proto3" json:"available_proxies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AvailableProxies) Reset() {
	*x = AvailableProxies{}
	mi := &file_hiveagent_hive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableProxies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableProxies) ProtoMessage() {}

func (x *AvailableProxies) ProtoReflect() protoreflect.Message {
	mi := &file_hiveagent_hive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableProxies.ProtoReflect.Descriptor instead.
func (*AvailableProxies) Descriptor() ([]byte, []int) {
	return file_hiveagent_hive_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableProxies) GetAvailableProxies() []*AvailableProxies_ProxyInfo {
	if x != nil {
		return x.AvailableProxies
	}
	return nil
}

type AvailableProxies_ProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyEndpoint string                 `protobuf:"bytes,1,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableProxies_ProxyInfo) Reset() {
	*x = AvailableProxies_ProxyInfo{}
	mi := &file_hiveagent_hive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableProxies_ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableProxies_ProxyInfo) ProtoMessage() {}

func (x *AvailableProxies_ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hiveagent_hive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableProxies_ProxyInfo.ProtoReflect.Descriptor instead.
func (*AvailableProxies_ProxyInfo) Descriptor() ([]byte, []int) {
	return file_hiveagent_hive_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AvailableProxies_ProxyInfo) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

var File_hiveagent_hive_proto protoreflect.FileDescriptor

var file_hiveagent_hive_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x68, 0x69, 0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x68, 0x69, 0x76, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x69, 0x76, 0x65, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x74, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x10,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73,
	0x12, 0x52, 0x0a, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x78, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x69,
	0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x78, 0x69, 0x65, 0x73, 0x1a, 0x32, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x92, 0x01, 0x0a, 0x0c, 0x48, 0x69, 0x76,
	0x65, 0x46, 0x6f, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x57, 0x68, 0x6f,
	0x41, 0x6d, 0x49, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x68, 0x69,
	0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x4a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6b, 0x76,
	0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x68, 0x69, 0x76, 0x65, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_hiveagent_hive_proto_rawDescOnce sync.Once
	file_hiveagent_hive_proto_rawDescData []byte
)

func file_hiveagent_hive_proto_rawDescGZIP() []byte {
	file_hiveagent_hive_proto_rawDescOnce.Do(func() {
		file_hiveagent_hive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hiveagent_hive_proto_rawDesc), len(file_hiveagent_hive_proto_rawDesc)))
	})
	return file_hiveagent_hive_proto_rawDescData
}

var file_hiveagent_hive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hiveagent_hive_proto_goTypes = []any{
	(*User)(nil),                       // 0: hiveagent.User
	(*AgentInfo)(nil),                  // 1: hiveagent.AgentInfo
	(*AvailableProxies)(nil),           // 2: hiveagent.AvailableProxies
	(*AvailableProxies_ProxyInfo)(nil), // 3: hiveagent.AvailableProxies.ProxyInfo
	(*common.AgentRouters)(nil),        // 4: common.AgentRouters
	(*emptypb.Empty)(nil),              // 5: google.protobuf.Empty
}
var file_hiveagent_hive_proto_depIdxs = []int32{
	0, // 0: hiveagent.AgentInfo.user:type_name -> hiveagent.User
	4, // 1: hiveagent.AgentInfo.routers:type_name -> common.AgentRouters
	3, // 2: hiveagent.AvailableProxies.available_proxies:type_name -> hiveagent.AvailableProxies.ProxyInfo
	5, // 3: hiveagent.HiveForAgent.WhoAmI:input_type -> google.protobuf.Empty
	5, // 4: hiveagent.HiveForAgent.GetAvailableProxies:input_type -> google.protobuf.Empty
	1, // 5: hiveagent.HiveForAgent.WhoAmI:output_type -> hiveagent.AgentInfo
	2, // 6: hiveagent.HiveForAgent.GetAvailableProxies:output_type -> hiveagent.AvailableProxies
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hiveagent_hive_proto_init() }
func file_hiveagent_hive_proto_init() {
	if File_hiveagent_hive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hiveagent_hive_proto_rawDesc), len(file_hiveagent_hive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hiveagent_hive_proto_goTypes,
		DependencyIndexes: file_hiveagent_hive_proto_depIdxs,
		MessageInfos:      file_hiveagent_hive_proto_msgTypes,
	}.Build()
	File_hiveagent_hive_proto = out.File
	file_hiveagent_hive_proto_goTypes = nil
	file_hiveagent_hive_proto_depIdxs = nil
}
